# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a745b4331dc934765fe9a05b397e26d49f35043ebd45c6c2b154aedbbed4155865e26446bcdc30bdba016f8fd108844fe1dfda0595313a8a032c4cd29736d89a

test:
  secret_key_base: 0d9aeb4329d9508983e1bbe1cd6380b5eb250b88b3e1fb5f72458367dd406ab5f5f645eac7eaddc752d206aa7a214298e6dc813a90d3753419b8adc528f31d7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
